Repository KDT3-final-project-team2/backend, pull requests merged in 2023-04, with the labels that each got.

#85 Test : Applicant Signup Test
  src/test/java/com/project/finalproject/applicant/controller/회원가입.java
  src/test/java/com/project/finalproject/applicant/service/Impl/회원가입.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#87 Test : Applicant MyInfo Test
  src/test/java/com/project/finalproject/applicant/controller/내_정보.java
  src/test/java/com/project/finalproject/applicant/service/Impl/내_정보.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#88 Test : Applicant MyInfoUpdate Test
  src/test/java/com/project/finalproject/applicant/controller/내_정보수정.java
  src/test/java/com/project/finalproject/applicant/service/Impl/내_정보수정.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#89 Test : Applicant ResumeSave Test
  src/test/java/com/project/finalproject/applicant/controller/이력서_등록.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_등록.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#90 Test : Applicant ResumeUpdate Test
  src/test/java/com/project/finalproject/applicant/controller/이력서_수정.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#91 Test : Applicant ResumeDownload Test
  src/test/java/com/project/finalproject/applicant/controller/이력서_조회.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_조회.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#92 Test : Applicant ResumeDelete Test
  src/test/java/com/project/finalproject/applicant/controller/이력서_삭제.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_삭제.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#93 Test : Applicant ApplyToJobpost Test
  src/test/java/com/project/finalproject/applicant/controller/지원하기.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원하기.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#94 Test : Applicant CancelApplyToJobpost Test
  src/test/java/com/project/finalproject/applicant/controller/지원취소.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원취소.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#95 Test : Applicant MyPage Test
  src/test/java/com/project/finalproject/applicant/controller/지원한_채용공고.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원한_채용공고.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#96 Fix: Changes related to Test
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/request/InfoUpdateRequestDTO.java
  src/main/java/com/project/finalproject/applicant/dto/request/JobpostIdRequestDTO.java
  src/main/java/com/project/finalproject/applicant/dto/request/SignupRequestDTO.java
  src/main/java/com/project/finalproject/applicant/dto/response/AppliedJobpostResponseDTO.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
  src/main/java/com/project/finalproject/application/entity/Application.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/jobpost/entity/Jobpost.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Bug

#98 Feature/#22 슈퍼관리자 약관 목록조회, 상세조회
  src/main/java/com/project/finalproject/term/entity/Term.java
  src/main/java/com/project/finalproject/term/exception/TermExceptionType.java
  src/test/java/com/project/finalproject/term/controller/TermController.java
  src/test/java/com/project/finalproject/term/dto/TermResDTO.java
  src/test/java/com/project/finalproject/term/exception/TermException.java
  src/test/java/com/project/finalproject/term/repository/TermRepository.java
  src/test/java/com/project/finalproject/term/service/TermService.java
  src/test/java/com/project/finalproject/term/service/TermServiceImpl.java
Labels: For: Backend, Priority: High, Status: In Progress

#99 Feature/#22 슈퍼관리자 약관 목록조회, 상세조회
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/term/controller/TermController.java
  src/main/java/com/project/finalproject/term/dto/TermResDTO.java
  src/main/java/com/project/finalproject/term/exception/TermException.java
  src/main/java/com/project/finalproject/term/repository/TermRepository.java
  src/main/java/com/project/finalproject/term/service/TermService.java
  src/main/java/com/project/finalproject/term/service/impl/TermServiceImpl.java
Labels: For: Backend, Priority: High, Status: In Progress

#100 fix: permitUrl /admin/term/** 수정
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: Backend

#101 fix: 약관 목록조회 List 형식으로 수정(repo,serviceimpl)
  src/main/java/com/project/finalproject/term/repository/TermRepository.java
  src/main/java/com/project/finalproject/term/service/impl/TermServiceImpl.java
Labels: For: Backend

#103 Fix : Changed local properties
  src/test/java/com/project/finalproject/applicant/service/Impl/내_정보.java
  src/test/java/com/project/finalproject/applicant/service/Impl/내_정보수정.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_등록.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_삭제.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_조회.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이메일_중복체크.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원취소.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원하기.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원한_채용공고.java
  src/test/java/com/project/finalproject/applicant/service/Impl/회원가입.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Maintenance

#107 Feat : Get running terms based on companyId
  src/main/java/com/project/finalproject/term/controller/TermController.java
  src/main/java/com/project/finalproject/term/dto/TermDetailResponseDTO.java
  src/main/java/com/project/finalproject/term/repository/TermRepository.java
  src/main/java/com/project/finalproject/term/service/TermService.java
  src/main/java/com/project/finalproject/term/service/impl/TermServiceImpl.java
  src/test/java/com/project/finalproject/term/dto/TermResDTO.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#112 Feat : Get running terms based on companyId Test
  src/test/java/com/project/finalproject/term/controller/사용중인_약관_불러오기.java
  src/test/java/com/project/finalproject/term/service/impl/사용중인_약관_불러오기.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#113 Feat/#17 지원자/기업/관리자 로그인 기능 구현 및 기타 수정
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtExceptionFilter.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
  src/main/java/com/project/finalproject/login/controller/ApplicantLoginController.java
  src/main/java/com/project/finalproject/login/controller/CompanyLoginController.java
  src/main/java/com/project/finalproject/login/repository/ApplicantLoginRepository.java
  src/main/java/com/project/finalproject/login/repository/CompanyLoginRepository.java
  src/main/java/com/project/finalproject/login/service/ApplicantLoginService.java
  src/main/java/com/project/finalproject/login/service/CompanyLoginService.java
  src/main/java/com/project/finalproject/signup/controller/CompanySignupController.java
  src/main/java/com/project/finalproject/signup/dto/CompanySignupReqDTO.java
  src/main/java/com/project/finalproject/signup/service/CompanySignupService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#114 fix: Application파일에 @EnableJpaAuditing 추가
  src/main/java/com/project/finalproject/FinalProjectApplication.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#115 Feature/#102 기업회원목록조회
  src/main/java/com/project/finalproject/company/controller/AdminController.java
  src/main/java/com/project/finalproject/company/dto/AdminCompanyRes.java
  src/main/java/com/project/finalproject/company/repository/CompanyRepository.java
  src/main/java/com/project/finalproject/company/service/AdminService.java
  src/main/java/com/project/finalproject/company/service/impl/AdminServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#117 Feat/#53 로그아웃 기능 구현 및 기타 수정
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
  src/main/java/com/project/finalproject/logout/controller/LogoutController.java
  src/main/java/com/project/finalproject/logout/dto/LogoutReqDTO.java
  src/main/java/com/project/finalproject/logout/service/LogoutService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature, Type: Maintenance

#120 Feat : Company get statistics for applications
  src/main/java/com/project/finalproject/application/entity/repository/ApplicationRepository.java
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/dto/ApplicationsForCompanyResponseDTO.java
  src/main/java/com/project/finalproject/company/repository/CompanyRepository.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/project/finalproject/jobpost/entity/Jobpost.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#124 Feat : Company get statistics for applications Test
  src/test/java/com/project/finalproject/company/controller/지원자_통계_조회.java
  src/test/java/com/project/finalproject/company/service/impl/지원자_통계_조회.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#128 Fix: Test error regarding jwtExceptionFilter
  src/test/java/com/project/finalproject/applicant/controller/내_정보.java
  src/test/java/com/project/finalproject/applicant/controller/내_정보수정.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_등록.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_삭제.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_수정.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_조회.java
  src/test/java/com/project/finalproject/applicant/controller/이메일_중복_체크.java
  src/test/java/com/project/finalproject/applicant/controller/지원취소.java
  src/test/java/com/project/finalproject/applicant/controller/지원하기.java
  src/test/java/com/project/finalproject/applicant/controller/지원한_채용공고.java
  src/test/java/com/project/finalproject/applicant/controller/회원가입.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Bug

#131 Fix : Fixed test codes related to recent changes
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_등록.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_삭제.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_조회.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원취소.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원하기.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원한_채용공고.java
  src/test/java/com/project/finalproject/term/controller/사용중인_약관_불러오기.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Maintenance

#132 [Feat] 지원자 상태 변경, 지원자 현황 조회
  src/main/java/com/project/finalproject/application/entity/Application.java
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/dto/ApplicationsForCompanyResponseDTO.java
  src/main/java/com/project/finalproject/company/dto/CompanyApplicationRequest.java
  src/main/java/com/project/finalproject/company/dto/CompanyApplicationResponse.java
  src/main/java/com/project/finalproject/company/exception/CompanyExceptionType.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
  src/test/java/com/project/finalproject/company/controller/지원자_통계_조회.java
  src/test/java/com/project/finalproject/company/service/impl/지원자_통계_조회.java
Labels: For: API, For: Backend, Priority: High, Status: Completed

#134 Feat/#109 회원탈퇴 기능 구현 및 기타 수정
  src/main/java/com/project/finalproject/applicant/entity/Applicant.java
  src/main/java/com/project/finalproject/company/entity/Company.java
  src/main/java/com/project/finalproject/logout/dto/LogoutReqDTO.java
  src/main/java/com/project/finalproject/logout/repository/LogoutRepository.java
  src/main/java/com/project/finalproject/resign/controller/ResignController.java
  src/main/java/com/project/finalproject/resign/dto/ResignDTO.java
  src/main/java/com/project/finalproject/resign/repository/ApplicantResignRepository.java
  src/main/java/com/project/finalproject/resign/repository/ApplicationResigngRepository.java
  src/main/java/com/project/finalproject/resign/repository/CompanyResignRepository.java
  src/main/java/com/project/finalproject/resign/service/ResignService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature, Type: Maintenance

#141 Feature/#102 기업회원목록조회 토큰 적용
  src/main/java/com/project/finalproject/company/controller/AdminController.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: API, For: Backend, Priority: Low, Status: Completed

#142 [Feat] 기업 회원 정보 출력, 기업 회원 정보 수정
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/dto/CompanyRequest.java
  src/main/java/com/project/finalproject/company/dto/CompanyResponse.java
  src/main/java/com/project/finalproject/company/entity/Company.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
Labels: For: API, For: Backend, Status: Completed

#143 Feat/#108 비밀번호 변경 및 초기화 기능 구현
  src/main/java/com/project/finalproject/applicant/entity/Applicant.java
  src/main/java/com/project/finalproject/company/entity/Company.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
  src/main/java/com/project/finalproject/password/controller/PasswordController.java
  src/main/java/com/project/finalproject/password/dto/PasswordDTO.java
  src/main/java/com/project/finalproject/password/repository/ApplicantPasswordRepository.java
  src/main/java/com/project/finalproject/password/repository/CompanyPasswordRepository.java
  src/main/java/com/project/finalproject/password/service/PasswordService.java
  src/main/java/com/project/finalproject/signup/service/CompanySignupService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature, Type: Maintenance

#144 Feature/#116 개인회원 목록조회(관리자)
  src/main/java/com/project/finalproject/company/controller/AdminController.java
  src/main/java/com/project/finalproject/company/dto/AdminApplicantRes.java
  src/main/java/com/project/finalproject/company/service/AdminService.java
  src/main/java/com/project/finalproject/company/service/impl/AdminServiceImpl.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: API, For: Backend, Priority: Low, Status: Completed, Type: Feature

#146 Fix: permitUrl 수정
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#147 Feature/#21 관리자 약관 등록 토큰적용
  src/main/java/com/project/finalproject/term/controller/TermController.java
  src/main/java/com/project/finalproject/term/dto/TermFormDTO.java
  src/main/java/com/project/finalproject/term/entity/Term.java
  src/main/java/com/project/finalproject/term/service/TermService.java
  src/main/java/com/project/finalproject/term/service/impl/TermServiceImpl.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Feature

#149 Fix: Typo in ApplicantWorkExperience enum ONE_YEAR
  src/main/java/com/project/finalproject/applicant/entity/enums/ApplicantWorkExperience.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Bug

#150 fix: url 오타 수정
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#151 Feature/#21 관리자 약관 수정, 기업회원 약관CRU
  src/main/java/com/project/finalproject/term/controller/TermController.java
  src/main/java/com/project/finalproject/term/dto/TermFormDTO.java
  src/main/java/com/project/finalproject/term/dto/TermResDTO.java
  src/main/java/com/project/finalproject/term/entity/Term.java
  src/main/java/com/project/finalproject/term/service/TermService.java
  src/main/java/com/project/finalproject/term/service/impl/TermServiceImpl.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Feature

#152 fix : 파일 업로드 버그 수정
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
Labels: For: API, For: Backend, Priority: Critical, Status: Completed, Type: Bug

#154 Fix : Finished Todo related to IDs and editted test cases
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/repository/ApplicantRepository.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
  src/test/java/com/project/finalproject/applicant/controller/내_정보.java
  src/test/java/com/project/finalproject/applicant/controller/내_정보수정.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_등록.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_삭제.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_수정.java
  src/test/java/com/project/finalproject/applicant/controller/이력서_조회.java
  src/test/java/com/project/finalproject/applicant/controller/이메일_중복_체크.java
  src/test/java/com/project/finalproject/applicant/controller/지원취소.java
  src/test/java/com/project/finalproject/applicant/controller/지원하기.java
  src/test/java/com/project/finalproject/applicant/controller/지원한_채용공고.java
  src/test/java/com/project/finalproject/applicant/controller/회원가입.java
  src/test/java/com/project/finalproject/applicant/service/Impl/내_정보수정.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_등록.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_삭제.java
  src/test/java/com/project/finalproject/applicant/service/Impl/이력서_조회.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원취소.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원하기.java
  src/test/java/com/project/finalproject/applicant/service/Impl/지원한_채용공고.java
  src/test/java/com/project/finalproject/company/controller/지원자_통계_조회.java
  src/test/java/com/project/finalproject/term/service/impl/사용중인_약관_불러오기.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#157 Fix/#17 Admin url에 ADMIN 접근권한설정, AdminLogin에 검증 추가
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/login/service/CompanyLoginService.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Bug

#158 Fix : Fixed Typo in referencing properties
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Bug

#156 Feat:#155 Company Email Duplicate Check
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#161 Fix : Excluded permit all url
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Bug

#162 Feature/#102 개인/기업회원 목록조회(관리자)
  src/main/java/com/project/finalproject/company/controller/AdminController.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Bug

#164 Fix/#22 admin url에 접근권한 추가
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/term/controller/TermController.java
Labels: For: API, For: Backend, Priority: Critical, Status: Completed, Type: Bug

#165 [fix] cors 문제 해결
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
  src/main/java/com/project/finalproject/global/exception/UtilException.java
  src/main/java/com/project/finalproject/global/jwt/JwtExceptionFilter.java
  src/main/java/com/project/finalproject/global/jwt/JwtFilter.java
  src/main/java/com/project/finalproject/global/jwt/JwtUtilException.java
  src/main/java/com/project/finalproject/global/jwt/JwtUtilExceptionType.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
  src/test/java/com/project/finalproject/applicant/service/Impl/내_정보.java
Labels: For: API, For: Backend, Priority: Critical, Status: Completed, Type: Bug

#166 Feature/#153 채용공고 삭제(관리자)
  src/main/java/com/project/finalproject/jobpost/controller/JobpostController.java
  src/main/java/com/project/finalproject/jobpost/service/JobpostService.java
  src/main/java/com/project/finalproject/jobpost/service/impl/JobpostServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#167 conf : https key file
  src/main/resources/keystore.p12
Labels: For: CI/CD

#168 #110 공고 조회 기능 구현 및 수정
  src/main/java/com/project/finalproject/global/exception/CustomExceptionHandler.java
  src/main/java/com/project/finalproject/global/jwt/JwtUtilException.java
  src/main/java/com/project/finalproject/global/jwt/JwtUtilExceptionType.java
  src/main/java/com/project/finalproject/jobpost/entity/enums/JobpostWorkExperience.java
  src/main/java/com/project/finalproject/searchpost/controller/SearchPostController.java
  src/main/java/com/project/finalproject/searchpost/dto/PostReqDTO.java
  src/main/java/com/project/finalproject/searchpost/dto/PostResDTO.java
  src/main/java/com/project/finalproject/searchpost/repository/SearchCompanyRepository.java
  src/main/java/com/project/finalproject/searchpost/repository/SearchPostRepository.java
  src/main/java/com/project/finalproject/searchpost/service/SearchPostService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature, Type: Maintenance

#170 Fix : Get At most 1 term
  src/main/java/com/project/finalproject/term/controller/TermController.java
  src/main/java/com/project/finalproject/term/dto/TermDetailResponseDTO.java
  src/main/java/com/project/finalproject/term/dto/TermTypeList.java
  src/main/java/com/project/finalproject/term/repository/TermRepository.java
  src/main/java/com/project/finalproject/term/service/TermService.java
  src/main/java/com/project/finalproject/term/service/impl/TermServiceImpl.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Maintenance

#171 Fix/#153 채용공고 삭제(관리자)
  src/main/java/com/project/finalproject/jobpost/controller/JobpostController.java
  src/main/java/com/project/finalproject/jobpost/service/JobpostService.java
  src/main/java/com/project/finalproject/jobpost/service/impl/JobpostServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Type: Bug

#172 fix: 필수입력항목 @NotNull, @NotBlank 설정
  src/main/java/com/project/finalproject/applicant/dto/request/SignupRequestDTO.java
  src/main/java/com/project/finalproject/company/dto/CompanyJobpostRequest.java
  src/main/java/com/project/finalproject/signup/dto/CompanySignupReqDTO.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Bug

#173 fix: @NotNull 설정추가
  src/main/java/com/project/finalproject/term/dto/TermFormDTO.java
Labels: For: Backend, Priority: Critical, Type: Bug

#175 Fix : Changed the way applicant resume is retrieved
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#176 Fix/#153 채용공고 삭제(관리자) parameter 수정
  src/main/java/com/project/finalproject/jobpost/controller/JobpostController.java
  src/main/java/com/project/finalproject/jobpost/service/JobpostService.java
  src/main/java/com/project/finalproject/jobpost/service/impl/JobpostServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Bug

#178 Feat:#111 일정 CRUD 기능 구현(달력)
  src/main/java/com/project/finalproject/calendar/controller/CalendarController.java
  src/main/java/com/project/finalproject/calendar/dto/CalendarReqDTO.java
  src/main/java/com/project/finalproject/calendar/dto/CalendarResDTO.java
  src/main/java/com/project/finalproject/calendar/entity/Calendar.java
  src/main/java/com/project/finalproject/calendar/repository/ApplicantCalendarRepository.java
  src/main/java/com/project/finalproject/calendar/repository/CalendarRepository.java
  src/main/java/com/project/finalproject/calendar/repository/CompanyCalendarRepository.java
  src/main/java/com/project/finalproject/calendar/service/CalendarService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature, Type: Maintenance

#179 #fix: 값 받아오는 방식 변경(body -> param)
  src/main/java/com/project/finalproject/searchpost/controller/SearchPostController.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#180 fix : exception 버그 수정
  src/main/java/com/project/finalproject/company/exception/CompanyExceptionType.java
  src/main/java/com/project/finalproject/global/exception/CustomExceptionHandler.java
Labels: For: API, Priority: Critical, Status: Completed, Type: Bug

#182 [Fix] 기업회원 지원자 목록에 지원서id 추가
  src/main/java/com/project/finalproject/company/dto/CompanyApplicationResponse.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Bug

#185 [Fix] 기업회원 지원자 목록에 지원서id 추가
  src/main/java/com/project/finalproject/application/entity/Application.java
  src/main/java/com/project/finalproject/company/dto/CompanyApplicationRequest.java
Labels: For: API, For: Backend, Status: Completed

#187 #fix: 달력 등록 로직에서의 오류 수정
  src/main/java/com/project/finalproject/calendar/service/CalendarService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#189 #188 결과메일 발송 기능 구현
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/dto/EmailReqDTO.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#190 Feature/#177 관리자 통계 기능 구현
  src/main/java/com/project/finalproject/applicant/repository/ApplicantRepository.java
  src/main/java/com/project/finalproject/company/controller/AdminController.java
  src/main/java/com/project/finalproject/company/repository/CompanyRepository.java
  src/main/java/com/project/finalproject/company/service/AdminService.java
  src/main/java/com/project/finalproject/company/service/impl/AdminServiceImpl.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#192 Feat : Applicant Custom Chatbot using chatGpt
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/ClassifierDTO.java
  src/main/java/com/project/finalproject/applicant/dto/request/ChatMessageRequestDTO.java
  src/main/java/com/project/finalproject/applicant/dto/request/OpenAIRequestDTO.java
  src/main/java/com/project/finalproject/applicant/dto/response/ChatMessageResponseDTO.java
  src/main/java/com/project/finalproject/applicant/dto/response/OpenAIResponseDTO.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantIntentClassifier.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantResponseGenerator.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#195 Feat : Company Custom Secretary using chatGpt
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/service/CompanyIntentClassifier.java
  src/main/java/com/project/finalproject/company/service/CompanyResponseGenerator.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#197 Fix : #196 Changed output url of applicant resume
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Maintenance

#198 [Feat] 채용공고 pdf 다운로드 기능 추가
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/dto/CompanyJobpostResponse.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
Labels: For: API, For: Backend, Priority: High

#199 #fix :AccessToken이 재발급되지 않는 오류 수정
  src/main/java/com/project/finalproject/global/jwt/JwtExceptionFilter.java
  src/main/java/com/project/finalproject/global/jwt/JwtFilter.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#202 Fix : #200 What to do intent
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#204 Fix : #203 Company Jobpost File Preview
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/impl/CompanyServiceImpl.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Bug

#206 Fix : #205 Added CompanyAddress in jobpost search
  src/main/java/com/project/finalproject/searchpost/dto/PostResDTO.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance
