Repository KDT3-final-project-team2/backend, pull requests merged in 2023-03, with the labels that each got.

#6 feature/#5 CI/CD setting. (main.yml)
  .github/workflows/main.yml
Labels: For: CI/CD, Priority: Low, Status: Completed, Type: Feature

#10 [Fix]#8 main.yml
  .github/workflows/main.yml
Labels: For: CI/CD, Priority: Low, Status: Completed, Type: Maintenance

#14 Docs: Github profile link and minor typo
  README.md
Labels: For: Backend, Priority: Low, Status: Completed, Type: Documentation

#28 Feat:/#23 Applicant info update
  build.gradle
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/request/ApplicantInfoUpdateRequest.java
  src/main/java/com/project/finalproject/applicant/dto/response/ApplicantInfoUpdateResponse.java
  src/main/java/com/project/finalproject/applicant/entity/Applicant.java
  src/main/java/com/project/finalproject/applicant/repository/ApplicantInfoUpdateRepository.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantInfoUpdateService.java
  src/main/java/com/project/finalproject/applicant/service/impl/ApplicantInfoUpdateServiceImpl.java
  src/main/resources/application-server.properties
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#30 feat/#17 complete signup feature
  src/main/java/com/project/finalproject/global/jwt/utils/JwtProperties.java
  src/main/java/com/project/finalproject/login/AuthController.java
  src/main/java/com/project/finalproject/login/login/applicant/ApplicantLoginRepository.java
  src/main/java/com/project/finalproject/login/login/applicant/ApplicantLoginService.java
  src/main/java/com/project/finalproject/login/login/company/CompanyLoginRepository.java
  src/main/java/com/project/finalproject/login/login/company/CompanyLoginService.java
  src/main/java/com/project/finalproject/login/signup/applicant/ApplicantSignupRepository.java
  src/main/java/com/project/finalproject/login/signup/applicant/ApplicantSignupService.java
  src/main/java/com/project/finalproject/login/signup/company/CompanySignupRepository.java
  src/main/java/com/project/finalproject/login/signup/company/CompanySignupService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#31 [Feat] 채용공고 조회 기능 구현
  src/main/java/com/project/finalproject/global/dto/ResponseDTO.java
  src/main/java/com/project/finalproject/jobpost/controller/JobpostController.java
  src/main/java/com/project/finalproject/jobpost/dto/JobpostRequestDTO.java
  src/main/java/com/project/finalproject/jobpost/dto/JobpostResponseDTO.java
  src/main/java/com/project/finalproject/jobpost/entity/Jobpost.java
  src/main/java/com/project/finalproject/jobpost/jobpost.txt
  src/main/java/com/project/finalproject/jobpost/repository/JobpostRepository.java
  src/main/java/com/project/finalproject/jobpost/service/JobpostService.java
  src/main/java/com/project/finalproject/jobpost/service/impl/JobpostServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed

#35 Feat:/#33 Get Company Info
  src/main/java/com/project/finalproject/company/controller/CompanyController.java
  src/main/java/com/project/finalproject/company/repository/CompanyRepository.java
  src/main/java/com/project/finalproject/company/service/CompanyService.java
  src/main/java/com/project/finalproject/company/service/Impl/CompanyServiceImpl.java
Labels: For: Frontend, Priority: Low, Status: Completed, Type: Feature

#36 Feat:/#33 Get Applicant Info
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/repository/ApplicantInfoUpdateRepository.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantInfoUpdateService.java
  src/main/java/com/project/finalproject/applicant/service/impl/ApplicantInfoUpdateServiceImpl.java
Labels: For: Frontend, Priority: Low, Status: Completed, Type: Feature

#37 feat/#17 revise packages
  .gitignore
  README.md
  src/main/java/com/project/finalproject/company/entity/Company.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtFilter.java
  src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
  src/main/java/com/project/finalproject/login/controller/LoginController.java
  src/main/java/com/project/finalproject/login/dto/LoginReqDTO.java
  src/main/java/com/project/finalproject/login/dto/LoginResDTO.java
  src/main/java/com/project/finalproject/login/login.txt
  src/main/java/com/project/finalproject/login/login/applicant/ApplicantLoginRepository.java
  src/main/java/com/project/finalproject/login/login/applicant/ApplicantLoginService.java
  src/main/java/com/project/finalproject/login/login/company/CompanyLoginRepository.java
  src/main/java/com/project/finalproject/login/login/company/CompanyLoginService.java
  src/main/java/com/project/finalproject/login/repository/ApplicantLoginRepository.java
  src/main/java/com/project/finalproject/login/repository/CompanyLoginRepository.java
  src/main/java/com/project/finalproject/login/service/ApplicantLoginService.java
  src/main/java/com/project/finalproject/login/service/CompanyLoginService.java
  src/main/java/com/project/finalproject/logout/controller/LogoutController.java
  src/main/java/com/project/finalproject/logout/dto/LogoutReqDTO.java
  src/main/java/com/project/finalproject/logout/repository/LogoutRepository.java
  src/main/java/com/project/finalproject/logout/service/LogoutService.java
  src/main/java/com/project/finalproject/signup/controller/SignupController.java
  src/main/java/com/project/finalproject/signup/dto/ApplicantSignupReqDTO.java
  src/main/java/com/project/finalproject/signup/dto/CompanySignupReqDTO.java
  src/main/java/com/project/finalproject/signup/repository/ApplicantSignupRepository.java
  src/main/java/com/project/finalproject/signup/repository/CompanySignupRepository.java
  src/main/java/com/project/finalproject/signup/service/ApplicantSignupService.java
  src/main/java/com/project/finalproject/signup/service/CompanySignupService.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#38 Fix : Changed file names
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/repository/ApplicantRepository.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/impl/ApplicantInfoUpdateServiceImpl.java
  src/main/java/com/project/finalproject/applicant/service/impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#39 Fix : Changed table names in entities
  src/main/java/com/project/finalproject/applicant/entity/Applicant.java
  src/main/java/com/project/finalproject/applicant/entity/Applications.java
  src/main/java/com/project/finalproject/applicant/entity/Favorite.java
  src/main/java/com/project/finalproject/company/entity/Terms.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#41 Feature/#17 Revise permitUrl
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#42 Fix : Bug
  src/main/java/com/project/finalproject/company/service/Impl/CompanyServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Bug

#50 Feat:/#43 Applicant Signup
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/request/SignupRequestDTO.java
  src/main/java/com/project/finalproject/applicant/entity/Applicant.java
  src/main/java/com/project/finalproject/applicant/entity/enums/ApplicantWorkExperience.java
  src/main/java/com/project/finalproject/applicant/repository/ApplicantRepository.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#51 Feat:/#47 Resume Related
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/entity/Applicant.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#57 Fix : Deleted Applicant Signup
  src/main/java/com/project/finalproject/signup/controller/SignupController.java
  src/main/java/com/project/finalproject/signup/dto/ApplicantSignupReqDTO.java
  src/main/java/com/project/finalproject/signup/repository/ApplicantSignupRepository.java
  src/main/java/com/project/finalproject/signup/service/ApplicantSignupService.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#58 Feat: Applicant Info Update
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/request/InfoUpdateRequestDTO.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#59 Fix : Added Encoding Password in applicant signup and info update
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#61 Fix : Applicant Email duplicate check
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#63 Fix: Added checkEmail url in permitUrl
  src/main/java/com/project/finalproject/global/config/SecurityConfig.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#64 Fix : 로그인관련 컨트롤러 분리 및 LoginResDTO 수정
  src/main/java/com/project/finalproject/login/controller/ApplicantLoginController.java
  src/main/java/com/project/finalproject/login/controller/CompanyLoginController.java
  src/main/java/com/project/finalproject/login/dto/LoginResDTO.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#66 Feat: Applicant get MyInfo
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/response/MyInfoResponseDTO.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature

#67 Fix : Changed Myinfo ResponseDTO
  src/main/java/com/project/finalproject/applicant/dto/response/MyInfoResponseDTO.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#70 Fix : In case of no applicant resume uploaded
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#71 Feat: #44 Applicant Mypage
  src/main/java/com/project/finalproject/applicant/controller/ApplicantController.java
  src/main/java/com/project/finalproject/applicant/dto/response/AppliedJobpostResponseDTO.java
  src/main/java/com/project/finalproject/applicant/service/ApplicantService.java
  src/main/java/com/project/finalproject/applicant/service/Impl/ApplicantServiceImpl.java
  src/main/java/com/project/finalproject/application/entity/Application.java
  src/main/java/com/project/finalproject/application/entity/repository/ApplicationRepository.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Feature
